services:
  proxy:
    image: traefik:v2.4
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.http.routers.dashboard.rule=Host(`traefik.docker.localhost`) && PathPrefix(`/`)"
      - "traefik.http.routers.dashboard.middlewares=auth@docker"
      - "traefik.http.routers.dashboard.service=dashboard@internal"
      - "traefik.http.routers.api.rule=Host(`traefik.docker.localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.api.middlewares=auth@docker"
      - "traefik.http.routers.api.service=api@internal"

  auth:
    image: node:14
    ports:
      - 3000:3000
      - 24678:24678
    command: npm run dev -- --host
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    labels:
      - "traefik.http.routers.auth.rule=Host(`auth.docker.localhost`)"
      - "traefik.http.middlewares.auth.forwardauth.address=http://auth:3000/auth"

  whoami:
    image: traefik/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
      - "traefik.http.routers.whoami.middlewares=auth@docker"
